services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: pgvector_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - postgres
  flask:
    build:
      context: ./flask/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: flask
    volumes:
      - ./flask:/usr/src/app
    command: flask run --host=0.0.0.0
volumes:
  postgres_volume:
